### ISSUE TITLE
Create Issue Templates

### ISSUE THREAD

**Issue by tchklovski** [predictionmachine/.github#1]
Not urgent, but I created this repo so we can have org-wide repo templates, as per [here](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file)

- Issue templates need to be under `./.github/ISSUE_TEMPLATE/` in this repo (which is also called .github)

**Comment by abhishekmishragithub** [comment]
Closed by #3 
🚀
